apiVersion: v1
kind: Service
metadata:
  app: jenkins
  namespace: parodrig-jenkins-oadp
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: jenkins
  sessionAffinity: None
  type: ClusterIP
