apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: jenkins
  namespace: parodrig-jenkins-oadp
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: jenkins
  wildcardPolicy: None
